### ISSUE TITLE
lxc exec lxd-ctrlp-1 -- kubeadm init --upload-certs | tee kubeadm-init.out wait too long

### ISSUE THREAD

**Issue by kenny19850514** [tsanghan/kubernetes-env#1]
I found that when initializing control-plane node by "lxc exec lxd-ctrlp-1 -- kubeadm init --upload-certs | tee kubeadm-init.out, seems waiting a long time with no progress".

Instead I pull the image first "lxc exec lxd-ctrlp-1 -- kubeadm config images pull" and then it works .

**Comment by tsanghan** [comment]
[![asciicast](https://asciinema.org/a/Adx3TObOKFIPpoI2PUrXcGpiB.svg)](https://asciinema.org/a/Adx3TObOKFIPpoI2PUrXcGpiB)

Since you did a `kubeadm config images pull`, you should have read the 3rd line of [preflight].
Just in case you missed it, here it is again.
`[preflight] This might take a minute or two, depending on the speed of your internet connection`
How long did you wait before you break out of `kubeadm init` and run `kubeadm config images pull`?

**Comment by kenny19850514** [comment]
I waited for around a minute. It should be my bad. 
Thanks ! and I tried it again, wait with some time, it works !
